<script setup></script>

<template>
  <span class="absolute top-[-6rpx] bell left-[4px] text-text3">
    <uni-icons type="notification-filled" color="" size="16" />
  </span>
</template>

<style lang="scss" scoped>
.bell {
  -webkit-animation: wobble-hor-top 2s infinite both;
  animation: wobble-hor-top 2s infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-12-28 15:53:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
@keyframes wobble-hor-top {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-5px) rotate(6deg);
    transform: translateX(-5px) rotate(6deg);
  }
  30% {
    -webkit-transform: translateX(4px) rotate(-6deg);
    transform: translateX(4px) rotate(-6deg);
  }
  45% {
    -webkit-transform: translateX(-4px) rotate(3.6deg);
    transform: translateX(-4px) rotate(3.6deg);
  }
  60% {
    -webkit-transform: translateX(4px) rotate(-2.4deg);
    transform: translateX(4px) rotate(-2.4deg);
  }
}
</style>
